// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: ulid.proto

package ulidpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ULID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Low  uint64 `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High uint64 `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
}

func (x *ULID) Reset() {
	*x = ULID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ulid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ULID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ULID) ProtoMessage() {}

func (x *ULID) ProtoReflect() protoreflect.Message {
	mi := &file_ulid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ULID.ProtoReflect.Descriptor instead.
func (*ULID) Descriptor() ([]byte, []int) {
	return file_ulid_proto_rawDescGZIP(), []int{0}
}

func (x *ULID) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *ULID) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

var File_ulid_proto protoreflect.FileDescriptor

var file_ulid_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x75, 0x6c, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x6c,
	0x69, 0x64, 0x22, 0x2c, 0x0a, 0x04, 0x55, 0x4c, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f,
	0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x69, 0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65,
	0x78, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x75, 0x6c, 0x69, 0x64, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x3b, 0x75, 0x6c, 0x69, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ulid_proto_rawDescOnce sync.Once
	file_ulid_proto_rawDescData = file_ulid_proto_rawDesc
)

func file_ulid_proto_rawDescGZIP() []byte {
	file_ulid_proto_rawDescOnce.Do(func() {
		file_ulid_proto_rawDescData = protoimpl.X.CompressGZIP(file_ulid_proto_rawDescData)
	})
	return file_ulid_proto_rawDescData
}

var file_ulid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ulid_proto_goTypes = []interface{}{
	(*ULID)(nil), // 0: ulid.ULID
}
var file_ulid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ulid_proto_init() }
func file_ulid_proto_init() {
	if File_ulid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ulid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ULID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ulid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ulid_proto_goTypes,
		DependencyIndexes: file_ulid_proto_depIdxs,
		MessageInfos:      file_ulid_proto_msgTypes,
	}.Build()
	File_ulid_proto = out.File
	file_ulid_proto_rawDesc = nil
	file_ulid_proto_goTypes = nil
	file_ulid_proto_depIdxs = nil
}
